#
# Configurations
#
CONFIG_UNISOC_DISP := m
CONFIG_DRM_SPRD_DPU0 := y
CONFIG_DRM_SPRD_DSI := y
CONFIG_TRUSTY_VIRTIO_IPC := y
CONFIG_DRM_SPRD_DUMMY := n
CONFIG_DRM_SPRD_WB_DEBUG := n
CONFIG_COMPAT := n
CONFIG_UNISOC_GSP := m

#
# Source List
#
sprd-drm-y := \
	disp_lib.o \
	sprd_bl.o \
	sprd_corner.o \
	sprd_crtc.o \
	sprd_dphy.o \
	sprd_dpu.o \
	sprd_drm.o \
	sprd_dsi_panel.o \
	sprd_dsi.o \
	sprd_gem.o \
	sprd_plane.o

INCLUDE_SUBDIR = \
	$(src)/dphy/Kbuild \
	$(src)/dpu/Kbuild \
	$(src)/dsi/Kbuild \
	$(src)/pike2/Kbuild \
	$(src)/qogirl6/Kbuild \
	$(src)/qogirn6pro/Kbuild \
	$(src)/sharkl3/Kbuild \
	$(src)/sharkl5/Kbuild \
	$(src)/sharkl5pro/Kbuild \
	$(src)/sharkle/Kbuild \
	$(src)/sysfs/Kbuild

#
# Build Options
#
ccflags-y := \
	-I$(srctree)/include/linux \
	-I$(srctree)/drivers/staging/android \
	-I$(src)

subdir-ccflags-y += -I$(srctree)/$(src)/../../../devfreq/apsys/

#
# Conditional Compilation
#
ifneq ($(CONFIG_UNISOC_DISP),n)
    ccflags-y += -DCONFIG_UNISOC_DISP=$(CONFIG_UNISOC_DISP)
endif

ifeq ($(CONFIG_DRM_SPRD_DPU0),y)
    ccflags-y += -DCONFIG_DRM_SPRD_DPU0=$(CONFIG_DRM_SPRD_DPU0)
endif

ifeq ($(CONFIG_DRM_SPRD_DSI),y)
    ccflags-y += -DCONFIG_DRM_SPRD_DSI=$(CONFIG_DRM_SPRD_DSI)
endif

ifeq ($(CONFIG_DRM_SPRD_DUMMY),y)
    INCLUDE_SUBDIR += $(src)/dummy/Kbuild
    ccflags-y += -DCONFIG_DRM_SPRD_DUMMY=$(CONFIG_DRM_SPRD_DUMMY)
endif

ifeq ($(CONFIG_DRM_SPRD_WB_DEBUG),y)
    ccflags-y += -DCONFIG_DRM_SPRD_WB_DEBUG=$(CONFIG_DRM_SPRD_WB_DEBUG)
endif

ifneq ($(CONFIG_UNISOC_GSP),n)
    ccflags-y += -DCONFIG_UNISOC_GSP=$(CONFIG_UNISOC_GSP)
endif

ifeq ($(CONFIG_TRUSTY_VIRTIO_IPC),y)
    sprd-drm-y += disp_trusty.o
    ccflags-y += -DCONFIG_TRUSTY_VIRTIO_IPC=$(CONFIG_TRUSTY_VIRTIO_IPC)
endif

ifeq ($(CONFIG_COMPAT),y)
    sprd-drm-y += sprd_ioc32.o
    ccflags-y += -DCONFIG_COMPAT=$(CONFIG_COMPAT)
endif

include $(INCLUDE_SUBDIR)

#
# Final Objects
#
obj-$(CONFIG_UNISOC_DISP) := sprd-drm.o
